server:
  host: localhost
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/weather
    username: postgres
    password: root123
    properties:
      driver: postgresql

  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 130000
      connectionTimeout: 310000
      leakDetectionThreshold: 310000


  main:
      allow-bean-definition-overriding: true
  liquibase:
    change-log: classpath:liquibase/master.yaml
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: public
    driver-class-name: org.postgresql.Driver

  jackson:
    serialization:
      FAIL-ON-EMPTY-BEANS: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          charset: UTF-8
          hbm2ddl:
            import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  sql:
    init:
      mode: never
  cache:
    type: redis
    redis:
      key-prefix: education.
      cache-null-values: false
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    ssl: false
    lettuce:
      pool:
        max-wait: 1000
        max-active: 1000
  activemq:
    broker-url:
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /ui
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: classpath:logback.xml
  level:
    com.figo.weatherapp.feign: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000
        errorDecoder: com.figo.weatherapp.feign.CustomFeignErrorDecoder


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
weather-service:
  http-client:
    read-timeout: 5000
    write-timeout: 5000
    connect-timeout: 5000
    response-timeout: 5000
  retry:
    max-retry: 3
    retry-interval: 5000
  urls:
    base-url: http://api.weatherapi.com/v1/current.json?key=${weather-service.key}&q={city}
  key: 4723df57a3b74b9f9a6173125230105


